### ISSUE TITLE
Roadmap to a more useable product

### ISSUE THREAD

**Issue by pastelsky** [pastelsky/bundlephobia#1]
Roadmap to 1.0 **iff** this idea catches on - 

- [x] Evaluate using webpack instead of rollup (webpack seems to be more tolerant towards incorrect module exports. For eg. rollup will fail to bundle fail to bundle some popular packages like [request](https://github.com/request/request)) due to duplicate export names.
- [x] Show better looking / more actionable error messages and avoid `alert()s`
- [x] Implement a better queuing system for bundling is a CPU intensive process and Heroku times out after 30s.
- [x] Evaluate using babili vs. the current UglifyJS harmony minifier. Bundling some packages fail due to usage of ES6/7 syntax unsupported by Uglify JS.
- [x] Make the source code less ugly.
- [x] Better design, maybe?

**Comment by rickmed** [comment]
5 stars for this project.

Can I suggest:
- Optionally having a list of modules for a grand total.
- Adding an estimate cost for unpacking/parsing js (specially useful on mobile devices).

**Comment by pastelsky** [comment]
Hey, @rickmed. Could you explain what you mean by your first point? I did initially think of allowing users to add multiple packages in a single query, but bundling is a CPU intensive process, and Heroku would most probably time out. 

Also I did think of adding parsing cost, but calculating so would require a dedicated machine so that times of different packages are comparable and independent of hosting environment and server load.

**Comment by rickmed** [comment]
1) I have no idea how this works, is it possible to make it as a static page?
2) I'm confused. How are you planning to calculate the parsing cost?

**Comment by pastelsky** [comment]
1. This cannot be a static page, as the calculations, bundling, minifying of modules happen on the server. 
2. A simple way to calculate the parse cost is to do a `eval` on the minified package code. But it would have to be done on an actual mobile device for good results.

**Comment by rickmed** [comment]
1) I'm pretty sure it can be done but most likely would change the whole app -just throwing the idea out there...
2) That sounds good. You could throttle CPU in devTools to get an estimate as well.

**Comment by jpdevries** [comment]
👍 for a feature request to somehow support multiple packages. Would be great to be able to do something like ?p=react@15.5.4,react-dom@15.5.4,rest of my packages... in your projects README.

Although there is the webpack visualizer for something similiar
https://chrisbateman.github.io/webpack-visualizer/

**Comment by zincli** [comment]
How about supporting package sets and let users make comparison for their different strategy

**Comment by evan-scott-zocdoc** [comment]
> Evaluate using babili vs. the current UglifyJS harmony minifier. Bundling some packages fail due to usage of ES6/7 syntax unsupported by Uglify JS.

I'd recommend using [`uglify-es`](https://www.npmjs.com/package/uglify-es) instead, as it handles the newer syntaxes.

**Comment by pastelsky** [comment]
A new version is out now - https://github.com/pastelsky/bundlephobia/releases/tag/v1.0.1

Solves some of the concerns noted above. Also, support for batch requests is possible to implement with the current architecture.

**Comment by joshgillies** [comment]
It would be cool if this project offered a way to compare two (or more?) packages.

**Comment by pastelsky** [comment]
Discounting a few quirks, Bundlephobia is pretty usable now. Closing this. Feature requests to go into a different issue.
